# use the latest ubuntu environment (18.04) available on travis
# dist: bionic

language: go

services:
  - docker

go:
  - "1.17"

# Only clone the most recent commit.
git:
  depth: 1

env:
  global:
    - APP_NAME=go-blockchain

branches:
  only:
    - dev-branch
